### ISSUE TITLE
Change stylesheet for better compatibility with Jenkins ANSI Color Plugin

### ISSUE THREAD

**Issue by gabrieleara** [jenkinsci/pipeline-graph-view-plugin#388]
### What feature do you want to see added?

Right now, when using in combination with the [Jenkins ANSI Color Plugin](https://plugins.jenkins.io/ansicolor/) the console log is not displayed properly.

Here is an example of a log that shows the issue:

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/11692280/e7804236-9705-4efd-990a-dd4f6c19b98b)

A simple fix is to apply the following changes to the CSS style of the log:
```css
.console-text {
  /* Move the padding here, so that multiple divs
     inside a console-text block do not have large
     paddings when interleaved with span blocks */
  padding-left: 15px;
  padding-right: 5px;
}

.console-text div {
  /* Change display mode so that spans and divs
     can interleave on the same line */
  display: inline-block;
  padding-left: 0pt !important;
  padding-right: 0pt !important;
}
```

Effect after injecting the above CSS code into the webpage:

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/11692280/3105e574-1d6e-40e0-aeb9-b612e86e1de1)
